### ISSUE TITLE
Add "pending" to test suites

### ISSUE THREAD

**Issue by Trevoke** [exercism/xscala#133]
The standard in exercism is to have each test suite have all but the first test marked "pending", allowing a clean output when running the tests in a TDD fashion.

A number of the tests in the Scala track do not have that keyword. This issue tracks the exercises that still need to be updated. No checkmark means the exercise still needs to be updated.
### To fix an exercise:
1. Choose an exercise from the list. Let us say you want to fix "**accumulate**".
2. Go to the test file, which will be under the path `exercises/accumulate/src/test/scala/accumulate_test.scala` in this repository. The paths for all exercises follow a similar convention. 
3. Edit the file, and add the keyword `pending` as the first line for all tests **except the first one**.
4. In your commit message, on the first line, write something like "Added pending keyword to accumulate test". In the next paragraph, write "Work on #133".
5. Open a pull request and tag me ( @trevoke ) in it, so that I can update this list when the PR gets merged in
### FAQ

Q: What happens if I go to the test file and there are already `pending` keywords?
A: Tell me in this issue so I can update the list!

Q: How do I edit the file and open a pull request?
A: You have two options. The simplest solution is to edit it straight in Github. This will do a number of things in the background, such as fork the repository for you and create a branch, and then allow you to open a pull request straight from there. The other option is more traditional: clone the repository locally, create a branch yourself, edit the file with your favorite editor, commit, push to your fork, then open a pull request from your fork.
### TODO

Provide links to documentation on edit-and-PR through Github interface.
- [X] Hello World
- [X] Bob
- [X] Hamming
- [X] Word Count
- [X] Pangram
- [X] Anagram
- [X] Nucleotide Count
- [X] Phone Number
- [X] Grade School
- [X] Robot Name
- [x] Leap
- [x] Etl
- [x] Meetup
- [x] Space Age
- [x] Grains
- [x] Gigasecond
- [x] Scrabble Score
- [x] Difference Of Squares
- [x] Accumulate
- [x] Sublist
- [x] Rna Transcription
- [x] Triangle
- [x] Binary
- [x] Roman Numerals
- [x] Prime Factors
- [x] Raindrops
- [x] Allergies
- [x] Atbash Cipher
- [x] Bank Account
- [x] Crypto Square
- [x] Kindergarten Garden
- [x] Robot Simulator
- [x] Queen Attack
- [x] Binary Search Tree
- [x] Hexadecimal
- [x] Largest Series Product
- [x] Luhn
- [x] Clock
- [x] Matrix
- [x] House
- [x] Minesweeper
- [x] Ocr Numbers
- [x] Octal
- [x] Trinary
- [x] Wordy
- [x] Food Chain
- [x] Linked List
- [x] Custom Set
- [x] Nth Prime
- [x] Palindrome Products
- [x] Pascals Triangle
- [x] Pig Latin
- [x] Pythagorean Triplet
- [x] Saddle Points
- [x] Say
- [x] Secret Handshake
- [x] Series
- [x] Sieve
- [x] Simple Cipher
- [x] Connect
- [x] Parallel Letter Frequency
- [x] Acronym
- [x] Forth

**Comment by kytrinyx** [comment]
:heart: :heart: :heart: This is nice and actionable. Would you update the issue to include the step-by-step description of what someone would need to do to fix a single exercise? This would make a great issue for someone who wants to make their first open source contribution.

**Comment by Trevoke** [comment]
Updated. What do you think?

**Comment by kytrinyx** [comment]
Holy smokes—this is so good.

**Comment by Trevoke** [comment]
Glad you like. Only thing to do now is ... To open issues for the TODO item :D (I couldn't find the documentation I'm looking for)

**Comment by ErikSchierboom** [comment]
@Trevoke It's [hacktober](https://hacktoberfest.digitalocean.com/), so I though I'd help you with this issue :) I'll probably submit the remaining ones later this week.

**Comment by Trevoke** [comment]
@ErikSchierboom Awesome! Thanks :)

**Comment by ErikSchierboom** [comment]
@Trevoke My pleasure!

**Comment by Trevoke** [comment]
Well that put a serious dent into the list! Thanks @ErikSchierboom ! :)

**Comment by ErikSchierboom** [comment]
You're welcome!

**Comment by ErikSchierboom** [comment]
@abo64 @ricemery @Trevoke I think this issue has been resolved. Could someone check?

**Comment by ricemery** [comment]
@ErikSchierboom  - Looks good to me. There were still a handful of exercises that were not shown as completed in the task list. I double checked all of them and marked them as completed.

Thanks

**Comment by ErikSchierboom** [comment]
:+1:
